"use client";

import Link from "next/link";
import { useState } from "react";
import { Button } from "@/components/ui";

type StatusKind = "forbidden" | "not-found";
const content: Record<StatusKind, { code: string; eyebrow: string; title: string; description: string; action: string }> = {
  forbidden: { code: "403", eyebrow: "Receta restringida", title: "Esta estación no está en tu menú.", description: "Tu rol actual no tiene permiso para preparar esta operación. El laboratorio mantiene sus ingredientes y acciones bajo control.", action: "Volver al panel" },
  "not-found": { code: "404", eyebrow: "Mise en place perdida", title: "No encontramos esa receta.", description: "La página que buscas no está en la despensa o pudo haber cambiado de ubicación. Regresa al inicio para continuar.", action: "Ir al inicio" },
};

export function GastronomyStatusPage({ kind, returnHref = "/dashboard" }: { kind: StatusKind; returnHref?: string }) {
  const [hasFoundEgg, setHasFoundEgg] = useState(false);
  const page = content[kind];
  return <main className="flex min-h-screen items-center justify-center overflow-hidden bg-gastro-surface-low p-5 text-gastro-primary"><section className="relative w-full max-w-4xl overflow-hidden rounded-3xl border border-gastro-outline-variant bg-white shadow-xl"><div aria-hidden="true" className="absolute -right-24 -top-24 size-64 rounded-full bg-orange-100" /><div aria-hidden="true" className="absolute -bottom-32 -left-24 size-72 rounded-full bg-gastro-error-container/50" /><div className="relative grid items-center gap-8 p-8 sm:p-12 lg:grid-cols-[1.15fr_0.85fr]"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-gastro-action">{page.eyebrow}</p><p className="mt-4 text-7xl font-bold tracking-tighter text-gastro-primary sm:text-8xl">{page.code}</p><h1 className="mt-4 max-w-lg text-3xl font-semibold tracking-tight sm:text-4xl">{page.title}</h1><p className="mt-4 max-w-xl text-sm leading-7 text-gastro-muted">{page.description}</p><div className="mt-7 flex flex-wrap gap-3"><Button onClick={() => window.history.back()} variant="secondary">Volver atrás</Button><Link className="inline-flex min-h-10 items-center justify-center rounded-lg bg-gastro-action px-4 text-sm font-semibold text-white transition-colors hover:bg-gastro-action-hover focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gastro-action focus-visible:ring-offset-2" href={returnHref}>{page.action}</Link></div></div><div className="relative mx-auto grid aspect-square w-full max-w-72 place-items-center"><div aria-hidden="true" className="absolute inset-5 rounded-full border-[14px] border-gastro-primary bg-orange-50 shadow-inner" /><div aria-hidden="true" className="absolute inset-x-10 bottom-10 h-20 rounded-b-[4rem] rounded-t-xl border-8 border-gastro-primary bg-white" /><div aria-hidden="true" className="absolute left-1/2 top-[22%] h-20 w-40 -translate-x-1/2 rounded-t-full border-x-8 border-t-8 border-gastro-primary bg-gastro-surface-low" /><span aria-hidden="true" className="relative mt-4 font-mono text-3xl font-bold text-gastro-action">{kind === "forbidden" ? "⛔" : "⌕"}</span><button aria-label="Encontrar el ingrediente secreto" className="absolute right-2 top-7 grid size-9 place-items-center rounded-full border border-gastro-outline-variant bg-white text-gastro-action shadow-sm transition-transform hover:scale-110 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gastro-action" onClick={() => setHasFoundEgg(true)} type="button">✦</button></div></div>{hasFoundEgg ? <p className="relative border-t border-gastro-outline-variant bg-orange-50 px-8 py-3 text-center font-mono text-xs text-gastro-action">Ingrediente secreto encontrado: Axel was here · sazonando el código.</p> : null}</section></main>;
}
